### ISSUE TITLE
How to use it on Lumen?

### ISSUE THREAD

**Issue by piavgh** [elibyy/tcpdf-laravel#24] opened 2017-05-05 08:47 UTC
Hi @elibyy 

Thank you for making this great wrapper

I tried to use this repo with Lumen by adding this line to bootstrap/app.php (of course after composer require elibyy/tcpdf-laravel)

$app->register(Elibyy\TCPDF\ServiceProvider::class);

I got these error:

> PHP Fatal error:  Class 'Config' not found in /Applications/XAMPP/xamppfiles/htdocs/lumen-api/vendor/elibyy/tcpdf-laravel/src/ServiceProvider.php on line 73
> 
> Fatal error: Class 'Config' not found in /Applications/XAMPP/xamppfiles/htdocs/lumen-api/vendor/elibyy/tcpdf-laravel/src/ServiceProvider.php on line 73

How can I resolve this?
Thank you very much.

**Comment by elibyy** [comment] 2017-05-09 08:47
fixed in [5.4.1](https://github.com/elibyy/tcpdf-laravel/releases/tag/5.4.1)

**Comment by elibyy** [comment] 2017-05-10 09:23
@piavgh  can you confirm that the issue is resolved?

**Comment by elibyy** [comment] 2017-07-03 16:53
fixed in [5.4.2](https://github.com/elibyy/tcpdf-laravel/releases/tag/5.4.2)

**Closed as completed by elibyy** 2017-07-03 16:53 UTC
