### ISSUE TITLE
Undefined property: Elibyy\TCPDF\TCPDFHelper::$h

### ISSUE THREAD

**Issue by davidwesdijk** [elibyy/tcpdf-laravel#25] opened 2017-05-05 12:38 UTC
Hi @elibyy (and others),

I'm recieving structural errors when calling the function below from a queue. When I'm calling the exact same function (with the same content, etc) to render it in my browser, it's going great. The content is simple plain html, no magic.

The error is:
```
ErrorException: Undefined property: Elibyy\TCPDF\TCPDFHelper::$h in ../vendor/tecnickcom/tcpdf/tcpdf.php:2793
```

This is the function; regarding other issues I tried the reset(); method, but no success. 
```
PDF::reset();
PDF::SetTitle('Foobar');
PDF::SetMargins(15,30,15);
PDF::AddPage();
PDF::writeHTML($this->content);
$this->content = PDF::Output('Foobar.pdf','S');
Storage::put($this->archive_file, $this->content);
```

Do you have an idea what might go wrong? Thank you for your time.

**Comment by Caroga** [comment] 2017-05-08 13:23
Having the same issue, would love to hear any way of debugging this?

**Comment by elibyy** [comment] 2017-05-09 09:56
hey there,
sorry for the delayed response,

1. please specify your versions.
2. I've performed a test on 5.4.1 with laravel 5.4.22 with the following:

`dispatch(new TestQueue());`

and in `TestQueue->handle`

```php
for ($i = 0; $i < 10; $i++)
{
   \PDF::reset();
  \PDF::SetTitle('Foobar');
  \PDF::SetMargins(15, 30, 15);
  \PDF::AddPage();
  \PDF::writeHTML('some text');
  $content = \PDF::Output('', 'S');
  \Storage::put('test' . $i . '.pdf', $content);
}
```

and it generated 10 files in my storage folder

**Comment by davidwesdijk** [comment] 2017-05-09 10:29
Thank you for your response!

I'm using:
- TCPDF-Laravel: 5.2.3
- Laravel: 5.2.45

```
PDF::reset();
PDF::SetAuthor('Foobar');
PDF::SetTitle('File '. $this->year);
PDF::SetMargins(15,30,15);
PDF::SetFont('dejavusans', '', 8, '', false);
PDF::setFontSubsetting(false);
PDF::SetDocInfoUnicode(false);
PDF::SetAutoPageBreak(true,15);
PDF::setFooterCallback( function($pdf) {
    $pdf->SetFont('dejavusans', '', 8, '', false);
    $pdf->setY(-15);
    $pdf->setX(170);
    $pdf->Cell(50, 10, 'Page '.$pdf->getAliasNumPage().' van '.$pdf->getAliasNbPages(), 0, 0, 'R', 0, '', 0, false, '', '');
});

PDF::AddPage();
PDF::writeHTML($this->content);

$this->archive_file = 'Foobar.pdf';
$this->content = PDF::Output('Naverrekening '. $this->year .'.pdf','S');

Storage::put($this->archive_file, $this->content);
$this->save();
```

This code is called from a queue and has to generate a single pdf-file. I keep getting the same Error Exception: Undefined property...
I'm running on a standard Linux provisioned AWS server managed by Laravel Forge, with no exotic configuration running. 

Do you have a chance to test with the specified versions? Thank you for your time.

**Comment by elibyy** [comment] 2017-05-09 10:36
hey,
i can perform debug and test on the specified versions, the only problem is that there's no laravel 5.2.45

also if you could provide redacted stack trace of the error it would help

**Comment by davidwesdijk** [comment] 2017-05-09 11:29
Hi Elibyy,
Thank you for your response, you can consider my Laravel version as 5.2.X (laravel/framework 5.2.45). 

This is the full stack trace:
```
ErrorException: Undefined property: Elibyy\TCPDF\TCPDFHelper::$h in /{path}/vendor/tecnickcom/tcpdf/tcpdf.php:2793
Stack trace:
#0 /{path}/vendor/tecnickcom/tcpdf/tcpdf.php(2793): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/{path}...', 2793, Array)
#1 [internal function]: TCPDF->SetAutoPageBreak(true, 15)
#2 /{path}/vendor/elibyy/tcpdf-laravel/src/TCPDF.php(40): call_user_func_array(Array, Array)
#3 /{path}/bootstrap/cache/compiled.php(6327): Elibyy\TCPDF\TCPDF->__call('SetAutoPageBrea...', Array)
#4 /{path}/app/Models/Recalculation/Recalculation.php(265): Illuminate\Support\Facades\Facade::__callStatic('SetAutoPageBrea...', Array)
#5 /{path}/app/Jobs/RenderRecalculationPdf.php(43): App\Models\Recalculation\Recalculation->renderPdf()
#6 [internal function]: App\Jobs\RenderRecalculationPdf->handle()
#7 /{path}/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#8 /{path}/bootstrap/cache/compiled.php(9874): Illuminate\Container\Container->call(Array)
#9 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\RenderRecalculationPdf))
#10 /{path}/bootstrap/cache/compiled.php(9970): call_user_func(Object(Closure), Object(App\Jobs\RenderRecalculationPdf))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\RenderRecalculationPdf))
#12 /{path}/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(App\Jobs\RenderRecalculationPdf))
#13 /{path}/bootstrap/cache/compiled.php(9875): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /{path}/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(41): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\RenderRecalculationPdf))
#15 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SqsJob), Array)
#16 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SqsJob.php(52): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#17 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(213): Illuminate\Queue\Jobs\SqsJob->fire()
#18 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(156): Illuminate\Queue\Worker->process('sqs', Object(Illuminate\Queue\Jobs\SqsJob), '6', 0)
#19 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop('sqs', 'MY_QUEUE', 0, '10', '6')
#20 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon('sqs', 'MY_QUEUE', 0, '10', '6')
#21 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(119): Illuminate\Queue\Worker->daemon('sqs', 'MY_QUEUE', 0, 128, '10', '6')
#22 /{path}/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(78): Illuminate\Queue\Console\WorkCommand->runWorker('sqs', 'MY_QUEUE', 0, 128, true)
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#24 /{path}/bootstrap/cache/compiled.php(1257): call_user_func_array(Array, Array)
#25 /{path}/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#26 /{path}/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /{path}/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /{path}/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /{path}/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /{path}/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /{path}/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /{path}/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 {main}
```

**Comment by elibyy** [comment] 2017-05-09 12:28
still working :| 

[this](https://gist.github.com/elibyy/50acf1a756f22f25c3a3432cc9b05aae) is my full simulation code

**Comment by Caroga** [comment] 2017-05-09 12:35
Hmm, this really acts very strange. As I have this as well, but it is inconsistent in its occurrence. 
What are you running your stack on, apache/nginx, which php version etc?

thank you for helping out tough!

**Comment by elibyy** [comment] 2017-05-09 12:51
round 1:
Windows 10 IIS
PHP 7.1.14

round 2:
UBUNTU Xenial NGINX
PHP 7.0.15

Can you also confirm that the sample isn't working too?
@Caroga

**Comment by Caroga** [comment] 2017-05-11 08:04
@elibyy Thanks for checking.
I've noticed this error occurs "randomly" on my side. I've had this error with the same setup as much as I did not have this.. 

Could it be memory related? I also run it on a AWS EC2 instance, managed by Forge. 
I've checked this both under windows and linux, running apache and nginx.

**Comment by elibyy** [comment] 2017-05-14 16:33
I've got an idea that might help you guys test,
since the major difference between my test and your actual code is that you are using HTML and I'm using text.

lets perform a quick test. on close TCPDF performs unset of all of it's variables  using the method `_destroy` (weird behavior but not my idea :| ), so let's add a `dd` call or `Log::debug` within that function of tcpdf to fully trace it

also note that TPCDF is not fully supported on PHP 7.x.x

hope that will help you guys solve the problem, closing this issue for now as it's related to TCPDF and not my wrapper.

if there's anything i can help, feel free to re-open this issue

**Comment by lukio3** [comment] 2019-01-08 16:51
I am getting the same issue. Only when tcpdf is used in queues. Outside of queues tcpdf is working fine.

Not attempting to re-open the issue here (for the reasons as stated @elibyy), but @Caroga and @dwesdijkschouten what did you decide to do? 

Many thanks

Luke

**Comment by elibyy** [comment] 2019-01-08 17:11
Hey @lukio3,
I'm always willing to try and help, I've never tested the logic on queues, but can you provide some more context that may assist in reproducing this bug (Preferably here for context) I can try and find how to fix it.

The information needed:
- PHP version
- Laravel version
- Library version
- Sample queue class simulating your logic

Also, There's no reason to *not* reopen this issue especially when there's an error in queues (Which is laravel feature and not TCPDF)

**Comment by lukio3** [comment] 2019-01-08 17:18
Hi @elibyy 

I'm happy to share what I can with you.

However, after reading your comments on [issue 22](https://github.com/elibyy/tcpdf-laravel/issues/22) I just tried adding `PDF::Reset();` to the beginning of my pdf building function.

With this, it processes a queue fine; I haven't had any fails yet. 

When I remove that function again, all jobs **apart from from the first one**, fail.

Luke

**Comment by lukio3** [comment] 2019-01-08 17:33
My version info:

**PHP version:** PHP 7.1.19 (cli) (built: Aug 17 2018 18:03:17) ( NTS )
**Laravel version:** "5.7.*",
**Library version:**  "elibyy/tcpdf-laravel": "^5.7",
**Sample queue class simulating your logic:**:

I don't have a queue class exactly. I simply have added the ShouldQueue contract to a Mailable class. 

My queue config is also the simplest one:
```

        'database' => [
            'driver' => 'database',
            'table' => 'jobs',
            'queue' => 'default',
            'retry_after' => 90,
        ],
```

However, I have attached the relevant files where I am using TCPDF-Laravel (I have put it into a Trait as I use it in a few places) and also the relevant Mailable class, implementing ShouldQueue.

[sample.zip](https://github.com/elibyy/tcpdf-laravel/files/2737819/sample.zip)

**Comment by Fluxlicious** [comment] 2020-03-23 11:06
I'm having the same issue but with the error `Undefined property: Elibyy\TCPDF\TCPDFHelper::$inxobj` when generating a PDF in a queued mail running from the commandline.
Like others already noticed, the error occurs the 2nd time try to use the PDF facade after you already created a PDF. The 2nd time laravel resolves the same TCPDF instance and somehow it's broken. I started digging into the TCPDF code, but it's so messy it's giving me a headache so i chose the quick way out by adding the following code after each PDF::Output() call. This clears the cached instance so when you call the PDF facade again you're getting a fresh instance.

```
// this goes right after your PDF::Output() call
app()->forgetInstance('tcpdf');
Facade::clearResolvedInstance('tcpdf');
```

Do note, since we are no longer reusing the TCPDF instance this could lead to memory issues. In production i have a daemon checking the mail:queue command that restart is if it fails.

**Comment by tkaratug** [comment] 2020-06-15 11:52
> Hi @elibyy
> 
> I'm happy to share what I can with you.
> 
> However, after reading your comments on [issue 22](https://github.com/elibyy/tcpdf-laravel/issues/22) I just tried adding `PDF::Reset();` to the beginning of my pdf building function.
> 
> With this, it processes a queue fine; I haven't had any fails yet.
> 
> When I remove that function again, all jobs **apart from from the first one**, fail.
> 
> Luke

This solution works for me. Thx. @lukio3

**Comment by dhofca** [comment] 2020-07-08 18:42
@Fluxlicious thanks! Perfect.

**Closed as completed** 2020-11-15 11:14 UTC

**Comment by acirinelli** [comment] 2024-03-04 21:18
I haven't encountered this error for a couple years, but it seems to be back.
